require 'preprocessor/preprocessor'
require 'preprocessor/cmd'
require 'preprocessor/trimmomatic'
require 'preprocessor/skewer'
require 'preprocessor/khmer'
require 'preprocessor/hammer'
require 'preprocessor/bbnorm'
require 'preprocessor/facs'
